image: seodisparate/gcc-runner

stages:
    - build
    - test

buildJob:
    stage: build
    tags:
        - docker
    script:
        - mkdir -p buildDebug
        - cd buildDebug
        - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=True ../src
        - make

testJob:
    stage: test
    tags:
        - docker
    script:
        - mkdir -p buildDebug
        - cd buildDebug
        - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=True ../src
        - make
        - ./UnitTests

